### ISSUE TITLE
Daemon issue

### ISSUE THREAD

**Issue by sc0ch** [citicashio/citicash#3] opened 2018-10-22 20:38 UTC
![image](https://user-images.githubusercontent.com/5249710/47317975-7ea25e80-d653-11e8-9c30-0d5def7384e2.png)

RPC wallet crashing after...

**Comment by salda** [comment] 2018-10-24 15:35
Thanks for reporting, I have seen it only once in the past. 
I am trying to solve it now. Do you know the steps, how to reproduce it?

**Comment by salda** [comment] 2018-10-24 16:01
Is the daemon the same version as the RPC-wallet? 
I have for example "Citicash 'Itynka' (v0.0.3.2-a81828a)" both (it is displayed in the daemon, when you call "help").

**Comment by sc0ch** [comment] 2018-10-26 07:56
> Thanks for reporting, I have seen it only once in the past.
> I am trying to solve it now. Do you know the steps, how to reproduce it?

Ubuntu 18.04.1, citicash compiled from source (NOT git clone), boost 1.65.1.

Same version of course.

**Comment by mzk** [comment] 2018-11-28 11:52
fixed in ce46d047d08032fa307cdd434ee7a27dbc1dd90b

**Comment by mzk** [comment] 2018-11-28 11:53
https://github.com/citicashio/gui-wallet-win/commit/37813719bbdb681e819a1d4f2d7ba36903265ad0

**Comment by salda** [comment] 2018-11-28 13:22
Thanks. Working on it now. Duplicate of #4

**Closed as completed by salda** 2018-11-28 13:22 UTC
